# change to list chars of your dataset or use default vietnamese chars
vocab: aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ-

# cpu, cuda, cuda
device: cuda

trainer:
    batch_size: 32
    print_every: 200
    valid_every: 200
    iters: 400000
    # where to save our model for prediction
    export: ./weights/resnet50_seq2seq_dataraw_400k_iter ##CHU Y DOI PATH
    checkpoint: ./checkpoint/resnet50_seq2seq_dataraw_400k_iter.pth ##CHU Y DOI PATH
    log: .log/resnet50_seq2seq_dataraw_400k_iter.log
    # null to disable compuate accuracy, or change to number of sample to enable validiation while training
    metrics: null

dataset:    
    # name of your dataset
    name: data
    # path to annotation and image
    data_root: ./data/new_train
    # resize image to 32 height, larger height will increase accuracy
    image_height: 32
    image_min_width: 32
    image_max_width: 512
    train_gt_path : ./data/train_gt.txt
    train_val_test_split: [0.97, 0.03, 0]
    transform_train : None
    transform_val : None
    transform_test : None

dataloader:
    num_workers: 48
    pin_memory: True


aug:
    image_aug: true
    masked_language_model: true

predictor:
    # disable or enable beamsearch while prediction, use beamsearch will be slower
    beamsearch: False

quiet: False 

# pretrain: 
#     id_or_url: 13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
#     md5: 7068030afe2e8fc639d0e1e2c25612b3
#     cached: /tmp/tranformerorc.pth

# weights: https://drive.google.com/uc?id=12dTOZ9VP7ZVzwQgVvqBWz5JO5RXXW5NY
weights: ./VietOCR/weights_infer/resnet50_seq2seq_data_raw_400k_iter_cer.pth

# backbone: resnet50
backbone: resnet50
cnn:
    ss:
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [2, 1]
        - [1, 1]          
    hidden: 256

seq_modeling: seq2seq
transformer:
    encoder_hidden: 256
    decoder_hidden: 256
    img_channel: 256
    decoder_embedded: 256
    dropout: 0.1

optimizer:
    max_lr: 0.001
    pct_start: 0.2
# python3 -m VietOCR.vietocr.train --config /solution/nnt/BK-Challenge/config/resnet_50.yml
